
version: '2'
services:
  media-bot:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: media-bot
    environment:
      - BOT_TOKEN=TELEGRAM_BOT_TOKEN
      - CHAT_ID=TELEGRAM_CHAT_IT
    volumes:
    - YOUR_PATH_TO_FOLDER:/app/dist/media
    networks:
      - media-network
networks:
  media-network:
    driver: bridge