
version: '2'
services:
  media-bot:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: media-bot
    environment:
      - BOT_TOKEN=TELEGRAMM_BOT_TOKEN
      - CHAT_ID=TELEGRAM_CHAT_ID
      - PROXY_HOST=SOCKS5_HOST
      - PROXY_PORT=SOCKS5_PORT
      - PROXY_LOGIN=SOCKS5_LOGIN
      - PROXY_PASSWORD=SOCKS5_PASSWORD
    volumes:
    - ~/mediaserver:/app/dist/media
    networks:
      - media-network
networks:
  media-network:
    driver: bridge